---
- name: create consul group
  become: yes
  become_user: root
  group:
    name: '{{ consul_agent_group }}'
    state: present

- name: create consul user
  become: yes
  become_user: root
  user:
    name: '{{ consul_agent_user }}'
    group: '{{ consul_agent_group }}'
    home: '{{ consul_agent_data_dir }}'
    state: present

- name: create directories
  become: yes
  become_user: root
  with_items:
    - d: '{{ consul_agent_etc_dir }}'
      m: '0755'
    - d: '{{ consul_agent_data_dir }}'
      m: '0755'
    - d: '{{ consul_agent_etc_pki_dir }}'
      m: '0700'
  file:
    path: '{{ item.d }}'
    state: directory
    owner: '{{ consul_agent_user }}'
    group: '{{ consul_agent_group }}'
    mode: '{{ item.m }}'

- name: install keys/certs
  when: consul_agent_secure
  include_role:
    name: andrewrothstein.sshkey
  vars:
    sshkey_become: True
    sshkey_pki_dir: '{{ consul_agent_pki_dir }}'
    sshkey_target_perms:
      owner: '{{ consul_agent_user }}'
      group: '{{ consul_agent_group }}'
    sshkey_target_dir: '{{ consul_agent_etc_pki_dir }}'
    sshkey_override_target_cert: cert.pem
    sshkey_override_target_key: key.pem

- name: configure templates...
  become: yes
  become_user: root
  template:
    src: '{{ consul_agent_template }}.j2'
    dest: '{{ consul_agent_etc_dir }}/consul.json'
    owner: '{{ consul_agent_user }}'
    group: '{{ consul_agent_group }}'
    mode: 0644

- include_tasks: '{{ consul_agent_init }}.yml'
